// Mock data for development/fallback when Supabase is not configured

export const mockCategories = [
  {
    id: '1',
    nombre: 'Batidos Naturales',
    descripcion: 'Batidos frescos hechos con frutas naturales',
    slug: 'batidos-naturales',
    is_active: true,
    display_order: 1,
  },
  {
    id: '2',
    nombre: 'Pasteles Artesanales',
    descripcion: 'Pasteles hechos a mano con ingredientes premium',
    slug: 'pasteles-artesanales',
    is_active: true,
    display_order: 2,
  },
  {
    id: '3',
    nombre: 'Bebidas Frías',
    descripcion: 'Bebidas refrescantes para el clima tropical',
    slug: 'bebidas-frias',
    is_active: true,
    display_order: 3,
  },
  {
    id: '4',
    nombre: 'Café Especial',
    descripcion: 'Café gourmet de origen único',
    slug: 'cafe-especial',
    is_active: true,
    display_order: 4,
  },
];

export const mockProducts = [
  {
    id: '1',
    nombre: 'Batido de Fresa',
    descripcion: 'Delicioso batido hecho con fresas frescas de temporada',
    short_description: 'Batido de fresa natural',
    precio: 95.00,
    categoria_id: '1',
    is_featured: true,
    stock: 50,
    rating_avg: 4.8,
    review_count: 24,
  },
  {
    id: '2',
    nombre: 'Pastel de Chocolate',
    descripcion: 'Pastel de chocolate oscuro con cobertura de ganache',
    short_description: 'Pastel chocolate premium',
    precio: 150.00,
    categoria_id: '2',
    is_featured: true,
    stock: 20,
    rating_avg: 4.9,
    review_count: 18,
  },
  {
    id: '3',
    nombre: 'Batido de Mango',
    descripcion: 'Refrescante batido de mango natural del trópico',
    short_description: 'Batido mango tropical',
    precio: 85.00,
    categoria_id: '1',
    is_featured: true,
    stock: 40,
    rating_avg: 4.7,
    review_count: 32,
  },
  {
    id: '4',
    nombre: 'Frappé Helado',
    descripcion: 'Bebida fría con café premium y hielo',
    short_description: 'Bebida fría premium',
    precio: 65.00,
    categoria_id: '3',
    is_featured: true,
    stock: 100,
    rating_avg: 4.6,
    review_count: 45,
  },
  {
    id: '5',
    nombre: 'Pastel de Vainilla',
    descripcion: 'Clásico pastel de vainilla con relleno de crema',
    short_description: 'Pastel vainilla clásico',
    precio: 120.00,
    categoria_id: '2',
    is_featured: false,
    stock: 25,
    rating_avg: 4.5,
    review_count: 15,
  },
  {
    id: '6',
    nombre: 'Café Americano',
    descripcion: 'Café espresso con agua caliente',
    short_description: 'Café americano',
    precio: 40.00,
    categoria_id: '4',
    is_featured: false,
    stock: 200,
    rating_avg: 4.4,
    review_count: 120,
  },
  {
    id: '7',
    nombre: 'Batido de Piña',
    descripcion: 'Tropical batido de piña fresca',
    short_description: 'Batido piña tropical',
    precio: 80.00,
    categoria_id: '1',
    is_featured: false,
    stock: 45,
    rating_avg: 4.6,
    review_count: 28,
  },
  {
    id: '8',
    nombre: 'Capuchino Especial',
    descripcion: 'Capuchino con espuma de leche vaporizada',
    short_description: 'Capuchino especial',
    precio: 55.00,
    categoria_id: '4',
    is_featured: false,
    stock: 150,
    rating_avg: 4.7,
    review_count: 85,
  },
];
